# Shared data volume container
data.container:
    image: xaamin/shared-volume
    container_name: data.container
    volumes:
    - ./shared:/shared
    - ./shared/sites:/etc/nginx/conf.d/

# Account MySQL container
mysql.gsg:
  image: mysql:5.7
  container_name: mysql.gsg
  hostname: mysql.gsg
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    # Uncomment if need create database and custom user on container first run
    #MYSQL_DATABASE: DBNAME
    #MYSQL_USER: USER
    #MYSQL_PASSWORD: PASSWD
  ports:
    - "3306:3306"
  volumes:
    - ./shared/databases/mysql:/var/lib/mysql
    - ./shared/config/mysql:/etc/mysql/conf.d

# Account PHP5-FPM container
doctors.stg:
  image: xaamin/php-fpm:7.1
  container_name: doctors.stg
  hostname: doctors.stg
  restart: always
  environment:
    # Domain to serve as upstream
    ACCOUNT: doctors.stg
    # Customize some resource limits. You'll see defaults
    DATE_TIMEZONE: America/Mexico_City
    REQUEST_TIMEOUT: 60
    MAX_INPUT_TIME: 60
    MEMORY_LIMIT: 128M
    POST_MAX_SIZE: 30M
  links:
    - mysql.gsg
  volumes:
    - ./shared/doctors.stg:/shared/doctors.stg
    - ./shared/doctors.stg/conf/php.ini:/etc/php/7.1/fpm/conf.d/10-custom_php.ini
    - ./shared/doctors.stg/conf/php_cli.ini:/etc/php/7.1/cli/conf.d/10-custom_php.ini

# NGinx
nginx:
  image: xaamin/nginx
  container_name: nginx
  hostname: nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    # - example.dev
    - doctors.stg
  volumes_from:
    - data.container