# Shared data volume container
data.container:
    image: xaamin/shared-volume
    container_name: data.container
    volumes:
    - ./shared/server:/shared

# Account MySQL container
mysql:
  image: mysql
  container_name: mysql
  hostname: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: tHezUfru#7E=e2Ud#
    # Uncomment if need create database and custom user on container first run
    #MYSQL_DATABASE: DBNAME
    #MYSQL_USER: USER
    #MYSQL_PASSWORD: PASSWD
  ports:
    - "3306:3306"
  volumes:
    - ./shared/databases/mysql:/var/lib/mysql
    - ./shared/config/mysql:/etc/mysql/conf.d

# Account PHP5-FPM container
example.test:
  image: xaamin/php-fpm
  container_name: example.test
  hostname: example.test
  restart: always
  environment:
    # Domain to serve as upstream
    ACCOUNT: example.test
    COMPOSER_HOME: "/home/www-data"
    # Customize some resource limits. You'll see defaults
    DATE_TIMEZONE: America/Mexico_City
    REQUEST_TIMEOUT: 60
    MAX_INPUT_TIME: 60
    MEMORY_LIMIT: 128M
    POST_MAX_SIZE: 30M
    # The User inside the docker
    DOCKER_USER: 'www-data'
    # The group inside the docker
    DOCKER_GROUP: 'www-data'
    # Your User ID, by default in the docker it's 0 for the root user
    HOST_USER_ID: "${HOST_USER_ID}"
    # Your Group ID, by default in the docker it's 0 for the root user
    HOST_GROUP_ID: "${HOST_GROUP_ID}"
  links:
    - mysql
  volumes:
    - ./shared/server/web/example.test:/shared/web/example.test
    - ./shared/server/web/example.test/conf/php.ini:/etc/php/7.0/fpm/conf.d/10-custom_php.ini
    - ./shared/server/web/example.test/conf/php_cli.ini:/etc/php/7.0/cli/conf.d/10-custom_php.ini

# NGinx
nginx:
  image: xaamin/nginx
  container_name: nginx
  hostname: nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  environment:
    # The User inside the docker
    DOCKER_USER: 'www-data'
    # The group inside the docker
    DOCKER_GROUP: 'www-data'
    # Your User ID, by default in the docker it's 0 for the root user
    HOST_USER_ID: "${HOST_USER_ID}"
    # Your Group ID, by default in the docker it's 0 for the root user
    HOST_GROUP_ID: "${HOST_GROUP_ID}"
  links:
    - example.test
  volumes_from:
    - data.container